/********************************************************************
* BcTreeDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BcTreeDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBcTreeDictionary();
extern void G__cpp_setup_inheritanceBcTreeDictionary();
extern void G__cpp_setup_typetableBcTreeDictionary();
extern void G__cpp_setup_memvarBcTreeDictionary();
extern void G__cpp_setup_globalBcTreeDictionary();
extern void G__cpp_setup_memfuncBcTreeDictionary();
extern void G__cpp_setup_funcBcTreeDictionary();
extern void G__set_cpp_environmentBcTreeDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../interface/BcTree.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BcTreeDictionaryLN_TClass;
extern G__linked_taginfo G__BcTreeDictionaryLN_TBuffer;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__BcTreeDictionaryLN_TObject;
extern G__linked_taginfo G__BcTreeDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TClonesArray;
extern G__linked_taginfo G__BcTreeDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_TLorentzVector;
extern G__linked_taginfo G__BcTreeDictionaryLN_TRefArray;
extern G__linked_taginfo G__BcTreeDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__BcTreeDictionaryLN_BcTreeCand;
extern G__linked_taginfo G__BcTreeDictionaryLN_BcTreeGENCand;
extern G__linked_taginfo G__BcTreeDictionaryLN_JpsiCand;
extern G__linked_taginfo G__BcTreeDictionaryLN_BcTreeHeader;
extern G__linked_taginfo G__BcTreeDictionaryLN_BcTree;

/* STUB derived class for protected member access */
